version: "3.6"
services:
  prod:
    image: tons/event-rooster-api
    build: .
    ports:
      - 8080:8080
    command: /bin/sh -c 'sleep 5 && /app/event-rooster-api'
    env_file:
      - .env

  test:
    build:
      context: .
      target: builder
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/sh -c 'go test -v ./tests'
    environment:
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}

  database:
    image: postgres:13-alpine
    tty: true
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

volumes:
  database: { }
