version: "3.6"
services:
  prod:
    image: tons/event-rooster-api
    build: .
    ports:
      - 8080:8080
    environment:
      GIN_MODE: release
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    env_file:
      - .env

  test:
    build:
      context: .
      target: build
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/sh -c 'go test -v ./tests'
    environment:
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}

  database:
    image: postgres:13-alpine
    tty: true
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
