environments:
  dev:
    values:
      - kubeContext: nuc
      - name: event-rooster-api
      - hostname: dev.api.lapio-groups.com
      - certIssuer: letsencrypt-prod
      - replicaCount: 1
      - postgresVersion: 10.1.1

  prod:
    values:
      - kubeContext: nuc
      - name: event-rooster-api
      - hostname: api.lapio-groups.com
      - certIssuer: letsencrypt-prod
      - replicaCount: 2
      - postgresVersion: 10.1.1

  feature:
    values:
      - kubeContext: nuc
      - name: event-rooster-api-{{ .Environment.Name }}-{{ requiredEnv "FEATURE_TAG" }}
      - hostname: {{ requiredEnv "FEATURE_TAG" }}.dev.api.lapio-groups.com
      - certIssuer: letsencrypt-staging
      - replicaCount: 1
      - postgresVersion: 10.1.1

releases:
  - name: "{{ .Values.name }}"
    namespace: event-rooster-{{ .Environment.Name }}
    chart: helm/
    kubeContext: "{{ .Values.kubeContext }}"
    values:
      - ingress:
          enabled: true
          hostname: {{ .Values.hostname }}
          certIssuer: {{ .Values.certIssuer }}
      - replicaCount: {{ .Values.replicaCount }}
    secrets:
      - secrets/{{ .Environment.Name }}/event-rooster-api.yaml

  - name: event-rooster-database
    namespace: event-rooster-{{ .Environment.Name }}
    chart: bitnami/postgresql
    verify: false
    version: "{{ .Values.postgresVersion }}"
    kubeContext: "{{ .Values.kubeContext }}"
    values:
      - persistence:
          size: 1Gi
    secrets:
      - secrets/{{ .Environment.Name }}/event-rooster-database.yaml

helmDefaults:
  recreatePods: true

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
