{{- if .Values.environmentVariables -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "event-rooster-api.fullname" . }}
  labels:
  {{- include "event-rooster-api.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.environmentVariables }}
  {{ $key }}: {{ $value | toString | b64enc }}
  {{- end }}
{{- end }}
